# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad9813afbb29e844be00cb0f12ff3a7af054955e52f10954a796accf07909acc3fac98440aa9605514a0503bc35fd84c3117a69aaa0314e734987c398b11dd9a

test:
  secret_key_base: 401e0eef86e3db7c514df5ad854c4db8e8979037d31f05de0fbdaada9a3245fc045db3d48493e8ebc3ab45b7488e3773134864fe097f9cfbd94fd5376468a618

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
